<?php

namespace Bonaire\Admin\Includes;

use PHPMailer;

/**
 * If this file is called directly, abort.
 */
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Include dependencies.
 */
if ( ! class_exists( 'PHPMailer' ) ) {
	include ABSPATH . 'wp-includes/class-phpmailer.php';
}

/**
 * The class responsible for email functionality.
 *
 * @since             1.0.0
 * @package           bonaire
 * @subpackage        bonaire/admin/includes
 * @author            Demis Patti <demis@demispatti.ch>
 */
final class Bonaire_Mail extends PHPMailer {
	
	/**
	 * The domain of the plugin.
	 *
	 * @var      string $domain
	 * @since    1.0.0
	 * @access   protected
	 */
	protected $domain;
	
	/**
	 * Holds the stored options.
	 *
	 * @var object $stored_options
	 * @since    1.0.0
	 * @access   private
	 */
	private $stored_options;
	
	/**
	 * Sets up an instance of the mailer class.
	 *
	 * @param null $exceptions
	 *
	 * @since 1.0.0
	 * @return PHPMailer $mail
	 */
	private function phpmailer( $exceptions = null ) {
		
		// Create Instance
		$mail = new parent;
		$stored_options = $this->stored_options;
		
		// Setup
		$mail->Host = $this->stored_options->smtp_host;
		$mail->CharSet = 'utf-8';
		$mail->SMTPAuth = true;
		$mail->Port = $this->stored_options->smtp_port;
		$mail->Username = $stored_options->username;
		$mail->Password = $stored_options->password;
		$mail->SMTPSecure = $stored_options->smtpsecure;
		$mail->isSMTP();
		
		// Debug
		if ( null !== $exceptions ) {
			$mail->SMTPDebug = 2;
			$mail->Debugoutput = function ( $str, $level ) {
				
				global $debug;
				$debug[] .= "$level: $str\n";
			};
			$mail->Timeout = 5;
		}
		
		return $mail;
	}
	
	/**
	 * Returns test mail data.
	 *
	 * @since 1.0.0
	 * @return object $data
	 */
	private function testmail_data() {
		
		$site_url = $this->url_to_domain( site_url() );
		// Test Data
		$data = (object) array();
		$data->to = $this->stored_options->from;
		$data->subject = __( 'Bonaire Testmail', $this->domain );
		$data->message = __( 'Howdy. This test message was generated by "Bonaire" for WordPress. Thanks for using this plugin!', $this->domain );
		$data->from = 'testmail@' . $site_url;
		$data->fromname = $this->stored_options->fromname;
		
		return $data;
	}
	
	/**
	 * Bonaire_Mail constructor.
	 *
	 * @param string $domain
	 * @param object $stored_options
	 */
	public function __construct( $domain, $stored_options ) {
		
		parent::__construct();
		
		$this->domain = $domain;
		$this->stored_options = $stored_options;
	}
	
	/**
	 * Sets up the mailer instance.
	 *
	 * @param object $data
	 * @param null $exceptions
	 *
	 * @since 1.0.0
	 * @return PHPMailer $mail
	 */
	private function setup( $data, $exceptions = null ) {
		
		$to = null !== $data->to ? (string) $data->to : $this->stored_options->from;
		
		$mail = $this->phpmailer( $exceptions );
		$mail->AddAddress( $to );
		$mail->AddReplyTo( $this->stored_options->from );
		$mail->Subject = strip_tags( $data->subject );
		$mail->Body = strip_tags( $data->message );
		$mail->From = $this->stored_options->from;
		$mail->FromName = $data->fromname;
		$mail->isSMTP();
		
		return $mail;
	}
	
	/**
	 * Shortens urls to something like 'smtp.gmail.com'
	 *
	 * @param string $url
	 *
	 * @since 1.0.0
	 * @return bool|string
	 */
	private function url_to_domain( $url ) {
		
		if ( substr( $url, 0, 8 ) === 'https://' ) {
			$url = substr( $url, 8 );
		}
		if ( substr( $url, 0, 7 ) === 'http://' ) {
			$url = substr( $url, 7 );
		}
		if ( substr( $url, 0, 4 ) === 'www.' ) {
			$url = substr( $url, 4 );
		}
		if ( strpos( $url, '/' ) !== false ) {
			$explode = explode( '/', $url );
			$url = $explode['0'];
		}
		
		return $url;
	}
	
	/**
	 * Sends a test mail.
	 *
	 * @since 1.0.0
	 * @return bool|\WP_Error
	 * @throws \Exception
	 */
	public function send_testmail() {
		
		$mail = $this->setup( $this->testmail_data(), true );
		
		try {
			$result = $mail->Send();
		} catch( Exception $e ) {
			
			return new \WP_Error( (string) $e->getCode(), (string) $e->getMessage() );
		}
		
		// If sending the test message failed
		if(false === $result) {
			
			return new \WP_Error( - 2, __( 'Sending test message failed:', $this->domain ) . ' ' . __( 'Could not reach the mail server.', $this->domain ) . '<br>' . __( 'Please make sure that you are connected to the internet, and that you\'ve tested the SMTP and IMAP settings with the respective buttons on this plugin\'s settings page.', $this->domain ) );
		}
		
		return $result;
	}
	
	/**
	 * Sends mail trough PHPMailer.
	 *
	 * @param object $data
	 *
	 * @since 1.0.0
	 * @return bool|\WP_Error
	 * @throws \Exception If saving the message failed
	 */
	public function send_mail( $data ) {
		
		$mail = $this->setup( $data );
		
		try {
			$result = $mail->Send();
		} catch( Exception $e ) {
			
			return new \WP_Error( $e->getCode(), $e->getMessage() );
		}
		
		// If sending the message failed
		if(false === $result) {
			
			return new \WP_Error( - 2, __( 'Sending test message failed:', $this->domain ) . ' ' . __( 'Could not reach the mail server.', $this->domain ) . '<br>' . __( 'Please make sure that you are connected to the internet, and that you\'ve tested the SMTP and IMAP settings with the respective buttons on this plugin\'s settings page.', $this->domain ) );
		}
		
		// Maybe save message in "Sent" folder
		if ( $result && 'yes' === $this->stored_options->save_reply ) {
			
			try {
				$result = $this->save_message( $mail, 'Sent' );
			} catch( Exception $e ) {
				
				return new \WP_Error( $e->getCode(), $e->getMessage() );
			}
		}
		
		return $result;
	}
	
	/**
	 * Saves the message in the "INBOX.Sent" folder.
	 *
	 * @param PHPMailer $mail
	 * @param null $folderPath
	 *
	 * @since 1.0.0
	 * @return bool|\WP_Error
	 */
	private function save_message( $mail, $folderPath = null ) {
		
		$mail->Host = $this->stored_options->imap_host;
		$mail->Port = $this->stored_options->imap_port;
		$mail->SMTPSecure = $this->stored_options->imapsecure;
		
		$message = $mail->MIMEHeader . $mail->MIMEBody;
		$path = 'INBOX' . ( null !== $folderPath ? '.' . $folderPath : '' );
		
		$use_ssl_certification_validation = '';
		if( 'nocert' === $this->stored_options->use_ssl_certification_validation ) {
			$use_ssl_certification_validation = '/novalidate-cert/norsh/service=imap/user=' . $mail->Username;
		}
		
		$imapStream = imap_open( '{' . $mail->Host . '/' . $mail->SMTPSecure . $use_ssl_certification_validation . '}' . $path, $mail->Username, $mail->Password );
		imap_append( $imapStream, '{' . $mail->Host . '}' . $path, $message );
		imap_close( $imapStream );
		
		if ( false === $imapStream ) {
			
			return new \WP_Error( 0, __( 'Failed to connect to host. Please review your settings and try again.', $this->domain ) );
		}
		
		return true;
	}
	
	/**
	 * Returns an instance of the mailer class.
	 *
	 * @param null $exceptions
	 *
	 * @since 1.0.0
	 * @return \PHPMailer
	 */
	public function get_phpmailer( $exceptions = null ) {
		
		return $this->phpmailer( $exceptions );
	}
	
}
